version: "3.9"

services:
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: inspectnote_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inspect_backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/inspectnote_dev
    volumes:
      - ./backend:/app
    command: yarn start:dev
volumes:
  postgres-data:
