version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dev_brief_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: dev_brief
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dev_brief_backend
    ports:
      - "3001:3000"
      - "5555:5555"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/dev_brief
    volumes:
      - ./backend:/app
    command: yarn start:dev
volumes:
  postgres-data:
