service: proposy-api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: proposy-api # AppSync API名
    authenticationType: API_KEY # 認証方式（APIキー）
    schema: schema.graphql # スキーマファイルの場所

dataSources:
  - type: AMAZON_DYNAMODB # データソースの種類
    name: CustomerTable # 内部で使用する名前
    config:
      tableName: { Ref: CustomerTable } # 実際のテーブル名（後で定義）

resources:
  Resources:
    CustomerTable: # CloudFormationリソース名
      Type: AWS::DynamoDB::Table # リソースタイプ
      Properties:
        TableName: ${self:service}-customers-${opt:stage, self:provider.stage} # 実際のテーブル名
        AttributeDefinitions: # 属性定義
          - AttributeName: id
            AttributeType: S # String型
        KeySchema: # プライマリキー
          - AttributeName: id
            KeyType: HASH # パーティションキー
        BillingMode: PAY_PER_REQUEST # 従量課金

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
