name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write # ブランチ作成とプッシュに必要
      pull-requests: write # PR作成に必要
      issues: write # Issue操作に必要
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得（ブランチ操作に必要）
          ref: develop # developブランチをチェックアウト

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch from devlop
        run: |
          # イシュー番号またはPR番号を取得
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            ISSUE_NUMBER=${{ github.event.issue.number }}
            BRANCH_NAME="claude-code/issue-${ISSUE_NUMBER}"
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]] || [[ "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            BRANCH_NAME="claude-code/pr-${PR_NUMBER}-fix"
          else
            # issue_commentの場合
            ISSUE_NUMBER=${{ github.event.issue.number }}
            BRANCH_NAME="claude-code/issue-${ISSUE_NUMBER}"
          fi

          # ブランチが既に存在する場合は削除
          if git show-ref --verify --quiet refs/heads/${BRANCH_NAME}; then
            git branch -D ${BRANCH_NAME}
          fi

          # devlopから新しいブランチを作成
          git checkout -b ${BRANCH_NAME}

          # ブランチ名を環境変数に保存
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # 必要に応じて追加のパラメータを設定
          # base_branch: devlop  # Claude Codeがサポートしている場合

      - name: Push changes if any
        if: success()
        run: |
          # 変更があるかチェック
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Claude Code: Automated changes based on @claude mention"
            git push origin ${BRANCH_NAME}
            
            # PRを作成するための情報を出力
            echo "Changes pushed to branch: ${BRANCH_NAME}"
            echo "You can create a PR from ${BRANCH_NAME} to devlop"
          else
            echo "No changes made by Claude Code"
          fi
